[boot]
# systemD can not run in WSL v1 Env.
systemd=false

[user]
# user to run as when first starting a WSL session.
default=CHANGE_ME

[interop]
# WSL will support launching Windows processes.
enabled=true
# WSL will add Windows path elements to the $PATH environment variable.
appendWindowsPath=false
